### ISSUE TITLE
CreateTopic is called

### ISSUE THREAD

**Issue by hpatoio** [php-enqueue/enqueue-dev#1022]
I've just installed and configured enqueue. Why is `CreateTopic` called ? I already created the SNS topic but enqueue call it anyway.

**Comment by Steveb-p** [comment]
`CreateTopic` does not actually create topic on broker, but instead it creates an object responsible for working with a topic / queue.

At least that's my assumption, since I'm not familiar with SNS/SQS - but almost every enqueue package behaves this way.

Unless it enqueue actually tries to create a topic on a broker and causes you an issue, I'm closing this.

**Comment by tyloo** [comment]
@Steveb-p : It actually does a `createTopic` query to the broker. Problem is, we have set our IAM credentials to not have the right to create a topic.

> AuthorizationError (client): User: arn:aws:sts::... is not authorized to perform: SNS:CreateTopic on resource: arn:aws:sns:eu-west-1:...:dev-messenger

**Comment by tyloo** [comment]
@Steveb-p : It actually does a `createTopic` query to the broker. Problem is, we have set our IAM credentials to not have the right to create a topic.

> AuthorizationError (client): User: arn:aws:sts::... is not authorized to perform: SNS:CreateTopic on resource: arn:aws:sns:eu-west-1:...:dev-messenger

**Comment by jderusse** [comment]
Actually, SNS component creates a topic in order to fetch the ARN:

https://github.com/php-enqueue/sns/blob/0568fa5168b39a48362a46db5638a5d0f586632f/SnsContext.php#L66-L77

which is called in 
https://github.com/php-enqueue/sns/blob/0568fa5168b39a48362a46db5638a5d0f586632f/SnsContext.php#L144-L151

Please reopen the issue.

**Comment by timgregg** [comment]
@Steveb-p It does create an sns topic is it possible to reopen this issue

**Comment by makasim** [comment]
fixed in #1147
