### ISSUE TITLE
Add ability to override log level in extensions

### ISSUE THREAD

**Issue by gnumoksha** [php-enqueue/enqueue-dev#1098]
## What
Extensions usually use `LoggerInterface::debug()`, but one might want to use a different level, in which case the extension should use `LoggerInterface::log()` instead.

## Why
Common scenarios:
- `debug` records are not processed/stored in a production environment
- the activation of some extensions (e.g. `LimitConsumerMemoryExtension`) might indicate a kind of error

**Comment by makasim** [comment]
What is your solution to this ?

**Comment by Steveb-p** [comment]
@makasim allowing to choose a specific log level would be enough, with default being `debug`.

`Logger->debug($message)` is a wrapper to `Logger->log('debug', $message)` call anyway as mentioned in the issue description.

**Comment by gnumoksha** [comment]
I can open a pull request, if you agree.

**Comment by makasim** [comment]
I don't think we should go this way. IMO it's better to copy\paste and customize the extension.

**Comment by Steveb-p** [comment]
@makasim I mostly agree. What we can do is put enqueue logs into a separate channel. This shouldn't affect users, especially since enqueue makes mostly use of debug logging. Other libraries - like Doctrine - do exactly that and I think did so since the early days.

We would need to tag logger with a specific channel for this to work.
https://symfony.com/doc/current/reference/dic_tags.html#monolog-logger

**Comment by gnumoksha** [comment]
Hmm, not sure if we are all talking about the same thing here. I didn't see the arguments against the "why" this change was proposed and I didn't get why symfony is a better reference instead of [PSR-3](https://www.php-fig.org/psr/psr-3/) and [its implementations](https://packagist.org/providers/psr/log-implementation).

Anyway, I will close this issue and do the workaround.
