### ISSUE TITLE
Set offset Symfony

### ISSUE THREAD

**Issue by vladanzivanovic** [php-enqueue/enqueue-dev#1133]
I saw there is a possibility to set offset manually, but didn't saw for Symfony integration. How can I achieve that?

**Comment by Steveb-p** [comment]
I'm assuming you're talking about kafka lib, since afaik it's the one that uses the concept of offsets. If no, then please disregard.

Manual offset is only viable for low level consumer, which this library doesn't use.

There are different opinions about using low level consumer. Most of them are that it should not be used unless a very particular feature of it is required - practically all the other functions work for high level one. If you want to set offset manually then unfortunately you'd need to construct low-level consumer and set it on your own.

Why do you need this functionality? What's your use case?
