### ISSUE TITLE
[job-queue] Job entity out-of-date

### ISSUE THREAD

**Issue by iainmckay** [php-enqueue/enqueue-dev#215]
We're creating a POC integration between enqueue and our app and have run in to an issue. This being that if there are multiple consumers working on jobs and answering the status calculation events, then because of the doctrine identity map the job entities can become stale. This creates the situation where 
the child job statuses never appear as complete and therefore neither do the root jobs.

We added a quick hack to `JobStorage::findJobById` to refresh the entity and this resolves the problem.

Perhaps we've configured something incorrectly but we've observed this issue before, and because of this we don't typically use the ORM for these sort of tasks.

Is this something other people have seen?

**Comment by makasim** [comment]
I don`t think that the problem is caused by `findJobById` method (still there might be problem). 
The `findJobById` could fetch a stale version of a job but it isn't important at all because later [CalculateRootJobStatusService](https://github.com/php-enqueue/enqueue-dev/blob/ffc9807dd6fb2e478e7dfb9739d47b0d82360a50/pkg/job-queue/CalculateRootJobStatusService.php#L38) service  does a [pessimistic lock](https://github.com/php-enqueue/enqueue-dev/blob/ffc9807dd6fb2e478e7dfb9739d47b0d82360a50/pkg/job-queue/Doctrine/JobStorage.php#L127) (inside the closure it has a fresh and completely synced  version of that same job).

**Comment by iainmckay** [comment]
I spent some more time digging through Doctrine and noticed it refreshes the entity when a pessimistic lock  is taken out so I should not be seeing the problem I am experiencing. 

The fact that my fix is working probably points to something in my application rather than the job-queue library. I'll dig through my application and if I find this not to be true I'll open a new issue and possibly be in a position to offer more information.

Thanks for your reply.
