### ISSUE TITLE
[amqp-ext] Do queue::close() when context::close() is called. 

### ISSUE THREAD

**Issue by makasim** [php-enqueue/enqueue-dev#25]
https://github.com/pdezwart/php-amqp/issues/267#event-953733318

**Comment by Wirone** [comment]
We're probably facing this issue right now. We're running several replicas of Docker image running consumer within Swarm stack. Each consumer is run with time limit, so it automatically stops working after limit passes, then Swarm restarts it again, and again. This is because we don't want to control memory usage, it's simpler to restart consumer from time to time.

But since introducing Swarm stack (earlier we've been using simple `docker-compose` stack with several consumers in it) we've got many Sentry events about `AMQPException: Library error: a socket error occurred`. Probably those consumers are not disconnected properly and there is exit code other than 0. This is weird, since the code did not change (only stack).

**Comment by makasim** [comment]
@pyrorules as far as I know there has not been a stable release of amqp ext with seg fault fix. So there is no way we can require it for now.

**Comment by Wirone** [comment]
How can it be part of `0.9` milestone if it's already released (0.9.1) and this issue is open?

**Comment by makasim** [comment]
@Wirone  removed it from 0.9 milestone
