### ISSUE TITLE
Symfony Bundle: amqp bunny doesn't stop the execution of the CLI command

### ISSUE THREAD

**Issue by lostfocus** [php-enqueue/enqueue-dev#303]
I'm running the Symfony Bundle with the following command:

`php bin/console --time-limit="now + 5 minutes" enqueue:consume -vvv`

and instead of just stopping after five minutes it keeps throwing a LimitConsumptionTimeExtension and stays around:

`[debug] [LimitConsumptionTimeExtension] Execution interrupted as limit time has passed. now: "2017-12-23T22:41:25+0000", time-limit: "2017-12-23T22:33:06+0000"`

It works fine with MySQL/Doctrine, but amqp/bunny keeps having this problem. Any idea what could be the problem?

**Comment by makasim** [comment]
That's most likely a bug. The reason why MySQL transports where AMQP not is because of how queue consumer subscribes to the queue. For AMQP it uses AMQP subscribe\consume API, where for the rest of transports it uses receive() method. 

https://github.com/php-enqueue/enqueue-dev/blob/fa2bd48af65e740d1041a5fc508bde872283f88e/pkg/enqueue/Consumption/QueueConsumer.php#L173

**Comment by lostfocus** [comment]
Just as an addendum: up until that Exception that doesn't stop the CLI command it works perfectly fine.
