### ISSUE TITLE
[Kafka] Reduce commit rate

### ISSUE THREAD

**Issue by koderoff** [php-enqueue/enqueue-dev#895]
Since committing every message is slow (and may slow down the consume rate) I'd like to commit say once per second or every 1000 messages. Is it possible?

I tried to use onResult event and change the result to Result::ALREADY_ACKNOWLEDGED but I could not call commitAsync from onPostConsume and onEnd events since there is no way to get consumer from the accessible context

**Comment by Steveb-p** [comment]
You can rely on Kafka broker commiting automatically. It will do so by default, so commiting (from client) can be disabled. That's why `commit.async` is recommended.

**Comment by koderoff** [comment]
Autocommiting messages is not really suits me as it may result in lost messages (lets say in case of app crash)

**Comment by Steveb-p** [comment]
> Autocommiting messages is not really suits me as it may result in lost messages (lets say in case of app crash)

On the other hand it's acceptable for you to process the message from Kafka more than once, I assume?

~~You've got a point there. The issue seems vaguely similar to `RdKafkaProducer` `poll` issue: we have a need to perform some action on `Consumer`s and `Producer`s, that is "outside" the usual process of acknowledging messages.~~

For the moment as a workaround for you, I'd suggest disabling `enable.auto.commit` and keeping `commit_async` enabled. That should cause the Kafka to still receive requests to commit a message offset and just will not respond to it (which is basically the reason for the delay - Kafka makes sure offset is commited, which is slow).

This way you'll make sure that message has been processed. Give it a try and see if it works.

**Comment by koderoff** [comment]
> On the other hand it's acceptable for you to process the message from Kafka more than once, I assume?

yes

> which is basically the reason for the delay

are you sure `enable.auto.commit` is the reason? In fact I have `enable.auto.commit` is already disabled but I still observe performance issues

**Comment by Steveb-p** [comment]
> are you sure `enable.auto.commit` is the reason? In fact I have `enable.auto.commit` is already disabled but I still observe performance issues

Consumer also has to be set into async mode via `commit_async`. 

If you're operating in Symfony bundle and using it's configuration, then just set it in config. Otherwise you'll have to call `RdKafkaConsumer::setCommitAsync(true)`.

**Comment by koderoff** [comment]
I have `commit_async: true` in my config (and it is true by default since version 0.9.9)

**Comment by koderoff** [comment]
> so commiting (from client) can be disabled

btw, it seems that disabling commits from the client is impossible in the current version. Am I wrong?

**Comment by Steveb-p** [comment]
> > so commiting (from client) can be disabled
> 
> btw, it seems that disabling commits from the client is impossible in the current version. Am I wrong?

Pretty much it was always like that. The only choice was between `commitAsync` and `commit` for Kafka Consumer.

> I have `commit_async: true` in my config (and it is true by default since version 0.9.9)

Yeah, but only for configuration.

Then I don't really know why it becomes slow for you. In my application I regularly handle thousands of small messages per second, so it should be performant. Granted, I operate on an older version of librdkafka, but I'm going to assume it's irrelevant for the time being.

Your Kafka broker has roughly default settings? Is there any possibility that network delay is responsible? Does it work fast enough if you comment out commiting messages (with - temporarily - `enable.auto.commit` enabled)?

**Comment by koderoff** [comment]
> Your Kafka broker has roughly default settings?

My kafka has completely default settings. It is run in my local k8s cluster.

> Does it work fast enough if you comment out commiting messages

It is work very fast when I reduce commit rate by the following extension
<img width="458" alt="image" src="https://user-images.githubusercontent.com/8904399/59165183-99610f00-8b20-11e9-8875-a5179ed39afc.png">
But the only problem is there is no way to get consumer to call commitAsync from `onPostConsume` and `onEnd`.

When I disable it the performance of my consumer slightly decreases and if I stop the consumer the proccess remains alive for some time (depends on commits count sent to the broker). At this time by monitoring consumer lag I see that kafka slowly processes remaining commits

**Comment by Steveb-p** [comment]
> EDIT: I'm trying to process about 8-10k messages per second

Alright, that's the kind of throughput where additional network calls, even due to `commitAsync`, might be undesirable.

So we would probably want to:
1. Allow disabling message commit on ACK entirely.
2. Provide a way of direct access to consumer instance for Extensions. I believe a similar approach to the one present in `EventDispatcher` from Symfony to be desirable (which is passing `EventDispatcher` instance that dispatched the event to listener as last argument [docs](https://symfony.com/doc/current/components/event_dispatcher.html#eventdispatcher-aware-events-and-listeners)).

@makasim is this approach acceptable? Your thoughts?

**Comment by makasim** [comment]
MessageResult object already has a consumer https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/enqueue/Consumption/Context/MessageResult.php#L21

Is it what you need?

**Comment by koderoff** [comment]
Sorry, my bad. I looked only at the available contexts in `onPostConsume` and `onEnd` events
