### ISSUE TITLE
Data is cached

### ISSUE THREAD

**Issue by maurotrentini** [php-enqueue/enqueue-dev#903]
I'm using the enqueue symfony bundle - when consuming messages, data is cached until I restart the consumer. For example if I change a contact's recipient email in the database, the consumer still send the email to the previous recipient unless I restart the consumer. **I'm not sure if this is the expected behavior? What could be a possible work around?**

`$this->contact = $this->contactRepository->getBySlugOrId($contactID);
        $this->logger->error($this->contact->getDetails()->getEmail());`

getEmail() always returns the old value, until I restart the consumer

**Comment by Steveb-p** [comment]
@maurotrentini is this even related to `enqueue` itself? It seems that your `contactRepository::getBySlugOrId` is run only once or caches data internally. This is not something that can be fixed in enqueue, nor should be.

If you're using Doctrine and using it's built-in `EntityRepository::find` or `EntityManager::find` methods, then do keep in mind that entities are cached in Doctrine. Those functions specifically **do not** make requests to database if an entity was already loaded earlier. You can circumvent this by calling `EntityManager::clear`.

I'm closing this unless you prove that it's something that `enqueue` can actually do something about.

**Comment by maurotrentini** [comment]
Thank you for your reply @Steveb-p 
The reason why I thought the issue was related to enqueue is that when I try to execute that bit of code directly from the Controller (instead of queuing and consuming it), it produces the expected result - the updated email is picked up correctly. If I execute the code from the Consumer, the exact same code doesn't pick up the updated email until I stop and restart the consumer.

I'm relatively new to Enqueue and I've been trying a few different things, including `EntityManager::clear` unsuccessfully so I thought perhaps there was something about Enqueue that I was missing. I can't really prove that the issue is related to enqueue, I just thought to ask, hoping that it would trigger some bells to somebody :)

**Comment by Steveb-p** [comment]
I'm almost 100% sure you're loading `$this->contact` only once or your repository method caches the instance. These are 2 reasons I can think of that you're entity is not updated.

**Comment by maurotrentini** [comment]
Thank you for pointing me in the right direction. I fixed the problem by adding the following line
`$this->entityManager->clear()`
just before
`$this->contact = $this->contactRepository->getBySlugOrId($contactID);`

I previously tried to clear the EntiryManager in the repository but strangely it did not work for me. 
Because in my case the EntityManager is set when the Consumer is instantiated, clearing EM inside the Consumer did the trick.

Thanks again!

**Comment by Mouerr** [comment]
Hello @maurotrentini i faced the same issue and i resolved it by adding **doctrine_clear_identity_map_extension : true** to enqueue.yml
```
enqueue:
    YOUR_TOPIC_NAME:
        transport: YOUR CONFIG
        client: YOUR CONFIG
        extensions:
            doctrine_clear_identity_map_extension: true
```
