### ISSUE TITLE
Define Queue in Producer

### ISSUE THREAD

**Issue by manseuk** [php-enqueue/enqueue-dev#923]
I am working on a project with micro services, I want to produce a message in one application and consume/process it in another. But i cannot do it with this bundle as I get `There is no route for command "<commandname>"` when attempting to send a command that has no processor defined.

Is it possible to define the route / queue details in the producer ?

**Comment by makasim** [comment]
not for now. Should be implemented: https://github.com/php-enqueue/enqueue-dev/issues/593

**Comment by newPOPE** [comment]
@manseuk workaround (I have same issue) may be to bind "blind" consumer in message producer. Something like this:

```
$client->bindCommand('request', function ($message) {}, 'some defined processor');
```

another issue waiting in processor naming because message is pushed to queue with processor property (default randomly generated) and must not match to recieve side. You can name that processors.
