### ISSUE TITLE
Remove message after n retry attempts

### ISSUE THREAD

**Issue by YuriyChmil** [php-enqueue/enqueue-dev#940]
Hey!
Is there any possibility to remove the message from the queue after n attempts failed to try to handle it?
For example, if 5 times the processor couldn't handle it must remove from queue.

Also, It is possible doesn't stop the consumer when an exception occurred? In this case, I want to try redeliver this message end try to handle it one more time? I know about **REQUEUE** options, put it push message to the new queue, but I want to push to the same queue. Is it possible?

**Comment by daemonfire300** [comment]
Hi there,

pushing this issue again, because:

I am using enqueue-redis and have a very simple Processor. How to I get enqueue to redeliver a Message for a later date, i.e., Message comes to processor, something temporarily did not work, let's process this message later.
What I tried:

  * Processeor::REQUEUE, but this puts a copy of the message into the queue and instantly tries to re-process it again.
  * Processor:REJECT, simply discards the message, never retries it
  * Throwing an exception in the processor, this also does not achieve the intended effect.

thaks in advance

**Comment by emrahoruc** [comment]
Something like a attempt counter is needed. Any solution?

**Comment by emrahoruc** [comment]
I found a solution in the php-enqueue/laravel-queue package. Uses the property field for attempts.
See:
https://github.com/php-enqueue/laravel-queue/blob/2c4ac43e0e4c65cc06406a45cab6d73991032622/src/Job.php#L62

Thank to all contributors.
