### ISSUE TITLE
Code duplication inside messages

### ISSUE THREAD

**Issue by Koc** [php-enqueue/enqueue-dev#96]
The files 
- https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/fs/FsMessage.php
- https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/redis/RedisMessage.php

are almost identical. How it possible reuse code, like trait or something else?

**Comment by makasim** [comment]
That true, but  I do not want to couple transports in any way. and I do not want to put more stuff to psr-queue lib.

**Comment by Koc** [comment]
It is ok put some common implementations to psr-layer. Something similar available for cache https://github.com/php-fig/cache-util/tree/master/src

**Comment by makasim** [comment]
Let's try it then.

**Comment by Koc** [comment]
Does messages implementations is different for different transports? Message is like value object, similar to cache item.

**Comment by makasim** [comment]
They are different. It may have additional stuff to what it the message interface require. 

For example. AMQP message has a delivery tag which is used while ack\reject.

**Comment by bendavies** [comment]
https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction :-)

**Comment by makasim** [comment]
Yeap, that's my favorite.

**Comment by makasim** [comment]
DRY is not a silver bullet and could do harm as well

**Comment by makasim** [comment]
I give it a thought and me decided not to introduce a trait. There are the reasons:

1. The most important. If we do a change in the trait because we need it in AMQP but at that time it breaks another Message from completely different transport. 
2. We remove duplication in easy to use and understand the code. Almost getters and setters
3. The code is not expected to change often. 

The solution: Provide a spec test case for messages so every implementation could be tested against it.  This is addressed here: https://github.com/php-enqueue/enqueue-dev/pull/102/files
